# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c369c549a320fbef60348871f3aeb39dc5edeb44555139a72e4c414ba93c3c96a3b0bfd3d9a5c029f9a31832ed2b24a36a31b0c3bce531e4f7bb07304b39e3e7

test:
  secret_key_base: 49c317e8583caeda703e0d59b52364018b1c9baa20ca3e7802f68be783d3d7fb94917421780540dfe99704865f5d2b2aafee2cf0f4f0f6903f6aeeee8234d453

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
